apiVersion: 1

# 仪表盘列表
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

# 仪表盘 provisioner
providers:
  - name: 'default'
    orgId: 1
    folder: '小Z简历'
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    options:
      path: /var/lib/grafana/dashboards
